# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TodoistCli < Formula
  desc "Todoist CLI"
  homepage "https://github.com/nyactl/todoist-cli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nyactl/todoist-cli/releases/download/v1.1.0/todoist-cli_1.1.0_darwin_amd64.tar.gz"
      sha256 "7203c8560d06cbd183fd5d235c59ce7aea91295c9770a2e749b38e848a1ec38a"

      define_method(:install) do
        bin.install "todoist-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nyactl/todoist-cli/releases/download/v1.1.0/todoist-cli_1.1.0_darwin_arm64.tar.gz"
      sha256 "805bce1fce58dc71fcf299c69723c57c34012aaf367bb40b611e31fd1da80e4a"

      define_method(:install) do
        bin.install "todoist-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyactl/todoist-cli/releases/download/v1.1.0/todoist-cli_1.1.0_linux_amd64.tar.gz"
      sha256 "e6053715a7800e5dda9f25176582ab7fb931138999495048a97845e9cdab40d6"
      define_method(:install) do
        bin.install "todoist-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyactl/todoist-cli/releases/download/v1.1.0/todoist-cli_1.1.0_linux_arm64.tar.gz"
      sha256 "dc4fe642eb5593596182052d062b08fbc9911eae95636b27eba438d1e61642a3"
      define_method(:install) do
        bin.install "todoist-cli"
      end
    end
  end

  test do
    system "#{bin}/todoist-cli", "--version"
  end
end
