# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mem < Formula
  desc "Fast, atomic notes in plain Markdown. Yours forever."
  homepage "https://github.com/nyactl/mem"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nyactl/mem/releases/download/v0.2.2/mem_0.2.2_darwin_amd64.tar.gz"
      sha256 "ea206416a9fb659e30c922769389bae496c2fb34d26e8d7dd4e29db5468fab46"

      define_method(:install) do
        bin.install "mem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nyactl/mem/releases/download/v0.2.2/mem_0.2.2_darwin_arm64.tar.gz"
      sha256 "6ca2d63aa76d1bfa3b20c21250ac6c1d0378033e255293b67d27298d7cf9b7dc"

      define_method(:install) do
        bin.install "mem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyactl/mem/releases/download/v0.2.2/mem_0.2.2_linux_amd64.tar.gz"
      sha256 "7c3139483c02c6bd42d932e98cd2d75d8c65f3c85ca8fdcd4e17e6531287f2a3"
      define_method(:install) do
        bin.install "mem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyactl/mem/releases/download/v0.2.2/mem_0.2.2_linux_arm64.tar.gz"
      sha256 "fbe7f479ce18ed33330ed2489400f7e9e1a18f309c338efc9edc4477a8665773"
      define_method(:install) do
        bin.install "mem"
      end
    end
  end

  test do
    system "#{bin}/mem", "--version"
  end
end
