# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mem < Formula
  desc "Fast, atomic notes in plain Markdown. Yours forever."
  homepage "https://github.com/nyactl/mem"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nyactl/mem/releases/download/v0.2.0/mem_0.2.0_darwin_amd64.tar.gz"
      sha256 "0d1852daf1b0e6bbccef6d0b006dff885b7973c226bf7b26e8d67e5f41df97e2"

      define_method(:install) do
        bin.install "mem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nyactl/mem/releases/download/v0.2.0/mem_0.2.0_darwin_arm64.tar.gz"
      sha256 "858f35fa84ad66273fb4337ada1285a4d8dab85159d921b17fc93970b05b0ed5"

      define_method(:install) do
        bin.install "mem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyactl/mem/releases/download/v0.2.0/mem_0.2.0_linux_amd64.tar.gz"
      sha256 "87775b691cbaeba6138a36fde12650439e44a8f12e4c073ebd3c3b445e249def"
      define_method(:install) do
        bin.install "mem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyactl/mem/releases/download/v0.2.0/mem_0.2.0_linux_arm64.tar.gz"
      sha256 "32ca9ac8a4fabe8d16d261cae9070fa49bc1e82c164d405fbb7fdbaf8c7c140b"
      define_method(:install) do
        bin.install "mem"
      end
    end
  end

  test do
    system "#{bin}/mem", "--version"
  end
end
