# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mem < Formula
  desc "Fast, atomic notes in plain Markdown. Yours forever."
  homepage "https://github.com/nyactl/mem-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nyactl/mem-cli/releases/download/v0.1.0/mem_0.1.0_darwin_amd64.tar.gz"
      sha256 "7179008a3dad7f57a43e70f8e0c2a9349020f9eb1dc3d0488af3d4e0c46edeb2"

      define_method(:install) do
        bin.install "mem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nyactl/mem-cli/releases/download/v0.1.0/mem_0.1.0_darwin_arm64.tar.gz"
      sha256 "48c071f54307e80096c5fe2e957d8736bfa5de630f047ad8c7148e40eda0bed8"

      define_method(:install) do
        bin.install "mem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyactl/mem-cli/releases/download/v0.1.0/mem_0.1.0_linux_amd64.tar.gz"
      sha256 "7a0ff813c0fd0a3c4eb221c3f6fab8b653b958538739da65e28cfd46e4c322bd"
      define_method(:install) do
        bin.install "mem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyactl/mem-cli/releases/download/v0.1.0/mem_0.1.0_linux_arm64.tar.gz"
      sha256 "845d3ce20962a7d587ae8df1a7dbfeb43e05418253ada03f68a2dae76c541ecf"
      define_method(:install) do
        bin.install "mem"
      end
    end
  end

  test do
    system "#{bin}/mem", "--version"
  end
end
