# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TodoistTui < Formula
  desc "lazygit-style terminal UI for Todoist"
  homepage "https://github.com/nyactl/todoist-tui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nyactl/todoist-tui/releases/download/v0.1.0/todoist-tui_0.1.0_darwin_amd64.tar.gz"
      sha256 "374aef3342b72218f76b4830a73112c79d1e84e5d52cb042522df5a88f560bbc"

      define_method(:install) do
        bin.install "todoist-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nyactl/todoist-tui/releases/download/v0.1.0/todoist-tui_0.1.0_darwin_arm64.tar.gz"
      sha256 "7289469e70a10fadb5616f568d659088feb9faabbcade2ca5918fd8193386ffe"

      define_method(:install) do
        bin.install "todoist-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyactl/todoist-tui/releases/download/v0.1.0/todoist-tui_0.1.0_linux_amd64.tar.gz"
      sha256 "ef5146f959dd0b4793ae81e930a8e04d3e7fa407297a5fe89b444183eb41ee17"
      define_method(:install) do
        bin.install "todoist-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyactl/todoist-tui/releases/download/v0.1.0/todoist-tui_0.1.0_linux_arm64.tar.gz"
      sha256 "e6a632aa4752fb08faee7800235f5be8b8af3999bafa648104347436e4a42058"
      define_method(:install) do
        bin.install "todoist-tui"
      end
    end
  end

  test do
    system "#{bin}/todoist-tui", "--version"
  end
end
